#include <stdlib.h>
#include <stdio.h>
#include <SDL.h>
#include <string.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <unistd.h>
#include <sys/wait.h>
#include "./navalmap/navalmap.h"
#include "./navalmap/nm_rect.h"
#include "./navalmap/navalmap.c"
#include "./navalmap/nm_rect.c"
